### ISSUE TITLE
Translate doesn't work for relative paths made with .rel

### ISSUE THREAD

**Issue by bojidar-bg** [fontello/svgpath#10]
If one attempts to translate a path and calls `.rel` nothing will happen.
````javascript
testPath = "m 70, 70 l 20, 20 l -20, 0 l 0, -20"
svgpath(testPath).translate(100, 100).toString()
// "M170 170l20 20-20 0 0-20" - as expected
svgpath(testPath).translate(100, 100).rel().toString()
// "m70 70l20 20-20 0 0-20" - now.. that one is not translated
svgpath( svgpath(testPath).rel().toString() ).translate(100,100).toString()
// "M170 170l20 20-20 0 0-20" - as expected
````

**Comment by puzrin** [comment]
> // "m70 70l20 20-20 0 0-20" - now.. that one is not translated

It shifted starting point of relative path ([170, 170] -> [70, 70]), and returned relative path. What's the problem with it? Why you decided this result is not correct?

**Comment by puzrin** [comment]
Ah, did not understood your example! Got it.

**Comment by puzrin** [comment]
Should be fixed now. Problem was, that first `m` in path should be always processed as absolute. I also changed `.rel()` to not lower case first 'M'.
