### ISSUE TITLE
New project starting from your library

### ISSUE THREAD

**Issue by kpym** [fontello/svgpath#19]
I just came to push a big rewrite of your library to my repo. 

First I want to thank you for your work and very good code.

I slightly renamed my project to [SVGPath(y)](https://github.com/kpym/svgpathy).

The final goal is to create a `gh-pages` with a GUI for this library ... some day ;)

**Comment by puzrin** [comment]
No problem! I'm glad you found some code useful. And thank you for your help with fixing bugs.
