### ISSUE TITLE
Parsing errors not detected

### ISSUE THREAD

**Issue by kpym** [fontello/svgpath#21]
I found two type of parse errors that the parser do not detect : 
- if their are more parameters than the minimal number, but not enough to complete the next segment.
- if the number is badly formatted like `.e3`, it is parsed silently to `NaN`.

`svgpath('M 0 0 0 H 0 .e3 -.e3').toString();` => `'M0 0H0 NaN NaN'`

**Comment by puzrin** [comment]
Should we return parse error or should we parse such numbers? Scientific float have different requirements about numbers before dot, i don't remember details for svg.

**Comment by kpym** [comment]
This is not a valid number. If you follow [W3C grammer](http://www.w3.org/TR/SVG/paths.html#PathDataBNF) (what you do in general) you have to throw error.

**Comment by kpym** [comment]
Now `svgpath('M0 0G 1').err` is `SvgPath: param should start with 0..9 or `.` (at pos 4)` and not `SvgPath: bad command 'G' (at pos 4)`

**Comment by puzrin** [comment]
Fixed in master. Any more errors or good for release?
