### ISSUE TITLE
Arcs processing problem

### ISSUE THREAD

**Issue by puzrin** [fontello/svgpath#23]
https://github.com/fontello/fontello/issues/479#issuecomment-193784669

Probably, issue with `a2c()`. To reproduce - drop svg examples to fontello.

**Comment by rlidwka** [comment]
Here is the exact way to reproduce this one:

```svg
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 1000 1000">
<path d="M148.7 277.9A228.7 113.2 90 1 0 159.3 734.8L837.5 734.8A228.5 113 90 1 0 837.5 277.9L159.3 277.9A228.5 113 90 0 0 148.7 277.9Z" />
</svg>
```

```js
var s = 'M148.7 277.9A228.7 113.2 90 1 0 159.3 734.8L837.5 734.8A228.5 113 90 1 0 837.5 277.9L159.3 277.9A228.5 113 90 0 0 148.7 277.9Z'

console.log(new SvgPath(s).scale(1, -1).translate(0, 850).abs().round(1).toString())
// M148.7 572.1A228.7 113.2 18.383 1 0 159.3 115.2L837.5 115.2A113 228.5 0 1 0 837.5 572.1L159.3 572.1A113 228.5 0 0 0 148.7 572.1Z
```

```svg
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 1000 1000">
<path d="M148.7 572.1A228.7 113.2 18.383 1 0 159.3 115.2L837.5 115.2A113 228.5 0 1 0 837.5 572.1L159.3 572.1A113 228.5 0 0 0 148.7 572.1Z" />
</svg>
```

**Comment by puzrin** [comment]
Looks like missed sign somewhere.

@kpym probably your fork has the same bug - flipping can trash arcs.

**Comment by kpym** [comment]
@puzrin Probably, if the problem is in a2c (I have not changed a2c), but it looks like the problem is in the way the transform works with arc. I'll check this ...

**Comment by puzrin** [comment]
100% not in a2c. See https://github.com/fontello/svgpath/issues/23#issuecomment-193897163. There are 2 problems:

- use improper part of esllipsis
- distortion due presition loss (in internal division `0 / 0`)

@rlidwka is investigating too.

**Comment by kpym** [comment]
@puzrin I have not checked, but if I remember well the `sweep-flag` is not changed by the transform. But it should be, because if the transformation is orientetion reversing (like `scale(1,-1)`) the `positif direction` change and the `sweep-flag` should be reversed ... to be checked.

**Comment by rlidwka** [comment]
@kpym, I believe the first issue I found is here:
https://github.com/fontello/svgpath/blob/master/lib/ellipse.js#L70-L77

L is `-2.41e-12`, l1 is `52303.68999999999, K is 52303.689999999995, and so it divides numbers both very close to zero.

If you add `rotate(0.00001)`, this issue goes away.

But there is a second issue somewhere, because arc does not actually flip. Maybe it has something to do with `sweep-flag`, thanks for the suggestion.

**Comment by rlidwka** [comment]
Here is the attempt to fix precision error (is there a better way?):
https://github.com/fontello/svgpath/commit/b50ec1791e4a650bee5041d58cc53f47caa4492a

As for `sweep-flag`, you're right, it needs to be flipped when one axis is flipped (e.g. `scale(1, -1)`, but not `scale(-1, -1)`). Trying to figure out the exact conditions now.

**Comment by puzrin** [comment]
https://github.com/fontello/svgpath/blob/master/lib/matrix.js#L47

`sx * sy < 0` ?

**Comment by kpym** [comment]
The exact condition is what I said: if the transform is orientation
preserving. This is equivalent to the determinant of the linear part is
positif.

**Comment by kpym** [comment]
Sorry I'm answering from my phone and I'm not very concentrated... I'll try to be more clear: if the determinant is negative, the `seep-flag` should be reversed.

**Comment by puzrin** [comment]
@kpym is my answer correct https://github.com/fontello/svgpath/issues/23#issuecomment-194334729 ?

`[ sx, *, *, sy, *, * ]` => need to check if sx*sy is negative or not?

**Comment by kpym** [comment]
@puzrin No. This is only valid for diagonal matrix. For general matrix you have to use the determinant.

**Comment by kpym** [comment]
The determinant is `m[0]×m[3]-m[1]×m[2]`.

**Comment by puzrin** [comment]
Seems to work now.

@kpym big thanks for your help!
