### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by 3rd-Eden** [fontello/svgpath#27]
This project is currently unable to run in browser due to the unicode variable names in the a2c.js file.  Browsers like the latest chrome are complaining about unknown/unidentified tokens in the source code as a result of this. 

Can we rewrite this to plain ol english so this project compiles in browsers?

**Comment by puzrin** [comment]
It's possible to rewrite, but i suspect the real problem is in wrong encoding header of webserver, or you can define utf-8 encoding explicit in `<script>` tag.

This package is used on fontello to import svg without problems, in all modern browsers.

**Comment by puzrin** [comment]
Also, AFAIK, `uglify-js` has option to produce ascii-only output https://github.com/markdown-it/markdown-it/blob/master/Makefile#L93 if you don't like to set encoding.

Let me know if this helps. IMHO, problem is outside of this package.

**Comment by 3rd-Eden** [comment]
I'm just running the file through browserify, and serving the bundle directly from disk so it does not serve up any addition headers for UTF-8 declarations. Simply changing the variables and recompiling the code resolved this issue hence me making the suggestion to just change it to prevent any unwanted hassle.

**Comment by puzrin** [comment]
I'd like to avoid such change because that reduce code maintainability. I think it's possible to make autogenerated shadow copy + alias in `package.json`.

> and serving the bundle directly from disk

Do you mean you open html directly from disk (as file:///...) with relative paths to js?
