### ISSUE TITLE
Suspicious code in arcs

### ISSUE THREAD

**Issue by puzrin** [fontello/svgpath#29]
https://github.com/fontello/svgpath/blob/2.2.1/lib/a2c.js#L15-L16

2 lines are the same.

- investigate why current tests show no error

**Comment by yGuy** [comment]
Looks as if the code only runs for normalized versions of u and v, thus both are always 1 and thus it never makes a difference - you could just as well remove that code completely and substitute "1" for it.

**Comment by puzrin** [comment]
Closed via https://github.com/fontello/svgpath/commit/319b21683ec0af3f73e6cecb86448b1306780a09.

Result was correct, but anyway thanks for notice about bad lines.
