### ISSUE TITLE
What are paths?

### ISSUE THREAD

**Issue by alexanderwallin** [fontello/svgpath#30]
Hi!

This library seems to do what I want to do, but I can't figure out how to use it, since I don't know what paths are in this case. There is a note on this in the README, and I think a brief explanation on what is actually is would be very helpful.

Thanks!

**Comment by alexanderwallin** [comment]
I take it it is raw path descriptor strings, like `c 50,0 50,100 100,100 c 50,0 50,-100 100,-100`?

**Comment by puzrin** [comment]
Yes. See https://github.com/fontello/svgpath/tree/master/test for examples
