### ISSUE TITLE
feature request: scale but keep line's width

### ISSUE THREAD

**Issue by creatxrgithub** [fontello/svgpath#36]
e.g. i have a font's svg path define:

```
<glyph glyph-name="uni4E38" unicode="&#x4e38;"
d="M855 1163v-78q0 -222 -31 -409q211 -157 211 -258q0 -64 -53 -64q-30 0 -66 57q-44 70 -116 150q-108 -432 -502 -706l-35 43q345 282 438 759q-107 97 -254 189l27 43q112 -56 241 -139q21 149 21 329v74h-458l-23 51h481v481q203 -3 203 -49q0 -25 -84 -53v-369h436
l76 96q125 -100 125 -127q0 -12.5508 -17 -24l-49 -33v-1054q0 -59 90 -59q97 0 111 61q30 126 43 379l55 -23q-2 -92 -2 -219q0 -108 16 -143q14 -32 54 -29q-3 -93 -64 -117q-50 -20 -207 -20q-138 0 -176 29q-39 23 -39 108v1124h-452z" />
```

i want to scale the path data, but keep the line 's width (Horizontal and vertical)

**Comment by puzrin** [comment]
I don't understand. This lib use content of `d` as input, and returns string (new value). It's your responsibility how to process other attr/styles.

**Comment by creatxrgithub** [comment]
the content of the d , is from a font's glyph data, when scale d , font's line 's width will also be changed, i wish to have a function to scale it but keep its line's width. i 'will upload images to explain.

![Untitled](https://user-images.githubusercontent.com/27437178/59005689-867ecf80-87ec-11e9-9517-5de18ead4684.png)

**Comment by puzrin** [comment]
Sorry, that's out of library scope. It applies some of available transforms and can not analyse visual look.
