### ISSUE TITLE
Why does the browser crash when I'm rotate somethings

### ISSUE THREAD

**Issue by jinjilynn** [fontello/svgpath#37]
svgpath.rotate(rotatenum).scale(scalenum).rel().toString()

something wrong?

**Comment by jinjilynn** [comment]
it doesn't throw any errors

**Comment by puzrin** [comment]
No idea. Could you provide full code sample and browser/os info?

**Comment by jinjilynn** [comment]
`d = "M786.0224 469.4016a49.7664 49.7664 0 0 1 0 85.1968L289.1776 852.5824a49.5616 49.5616 0 0 1-75.1616-42.5984v-595.968a49.5616 49.5616 0 0 1 75.1616-42.5984l496.8448 297.984z"`

This is a triangular svg path

` const d = svgpath.rotate(-90).scale(0.04).rel().toString()` 

when i console d , i get the following results,
`M18.776064-31.440896a1.990656 1.990656 0 0 1 3.407872 2.0867197683519443e-16l11.91936 19.873791999999998a1.982464 1.982464 0 0 1-1.7039360000000001 3.0064640000000002l-23.83872-1.4597006071884995e-15a1.982464 1.982464 0 0 1-1.7039359999999997-3.0064640000000002l11.919360000000001-19.873792z`

Browser crash is my problem, but I found that there was no separator between 18.776064 and -31.440896.

**Comment by puzrin** [comment]
Separators are not needed when end of sequence can be understood (when next character makes previous content invalid => effect the same as with space)

**Comment by jinjilynn** [comment]
All right, thank you.
