### ISSUE TITLE
For in-browser use, do we have a bundled JS file served anywhere?

### ISSUE THREAD

**Issue by tracyhenry** [fontello/svgpath#38]
https://www.jsdelivr.com/package/npm/svgpath doesn't have any. 

I know we can use something like [browserify](http://browserify.org/), but it'll be great if there is an official/default one served on platforms like jsdelivr.

**Comment by puzrin** [comment]
I would not like to support such feature for small libs. That's not convenvenient for maintenance, and such libs are used standalone very rare.

**Comment by tracyhenry** [comment]
hmm... you run bundle once for every release, why would that be much inconvenient?

Also, it's quite common for people to use this library directly in the browser, isn't it? An online JS library would make those people's lives much easier. Otherwise, they'd have to run bundle themselves, or simply copy paste your source code (like what I did...).

**Comment by puzrin** [comment]
For many years nobody except you asked such feature. Please, browserify at your side.

**Comment by tracyhenry** [comment]
"For many years nobody except you asked such feature"... 
This is not how you should evaluate the importance of a feature. People might walk away if they have to browserify, and might just be silent about taking the pain to browserify. 

If you don't care enough about a feature request, and don't want to spend time learning something you don't understand, you're better off just saying you don't have time. Coming up with random reasons like these will only show your arrogance and ignorance.

**Comment by puzrin** [comment]
Please, do the fork instead of teach me what i should and should not do. You != all users. If you have default permissions to post here, that does not make all your comments clever and welcome.
