### ISSUE TITLE
feature request: non-scaling-stroke

### ISSUE THREAD

**Issue by creatxrgithub** [fontello/svgpath#39]
i wish to have a feature 'non-scaling-stroke' result data to keep lines width while scaling.

thanks.

**Comment by puzrin** [comment]
That's out of this package scope. It's for math transforms only, not for visual ones.

**Comment by creatxrgithub** [comment]
while it is able to do for visual, it must be able to calculate by math, i wish someone could implement it.

**Comment by puzrin** [comment]
This library operates on lower level, it does not know anything about strokes at all. It transforms lines with zero width. If such lines form contour - that's completely different story, not for this lib.

**Comment by creatxrgithub** [comment]
i found a picture that could express my intention

![mt_images-article_variablefonts_glyphanimation_v2](https://user-images.githubusercontent.com/27437178/71386546-9dd0af00-25bc-11ea-8ae1-7812bf3b416f.gif)
