### ISSUE TITLE
Shorthand notation ends up in missing parameters

### ISSUE THREAD

**Issue by mathieudutour** [fontello/svgpath#41]
The following path `M11.467 3.727c.289.189.37.576.181.865l-4.25 6.5a.625.625 0 01-.943.12l-2.75-2.5a.625.625 0 01.84-.925l2.208 2.007 3.849-5.886a.625.625 0 01.865-.181z` gives a parsing error `SvgPath: numbers started with '0' such as '09' are ilegal (at pos 59)` while being correctly rendered by browsers.

`a.625.625 0 01.84-.925` is supposed to be parsed as `a 0.625 0.625 0 0 1 0.84 -0.925`. Notice how `01.` become `0 1 0.`. Instead svgpath parses it as `a 0.625 0.625 0 1.84 -0.925`, and so misses 2 params.

**Comment by puzrin** [comment]
Thanks for report. Interesting. What software used to generate such images? Some kind of SVG size optimizer?

**0 01.84-.925**

I can understand `01.84` => `0 1.84`. But `0 1 0.84`... May be you know part of SVG spec, explaining that?

**Comment by mathieudutour** [comment]
> What software used to generate such images? Some kind of SVG size optimizer?

I don't know but maybe @hadihallak does.

> May be you know part of SVG spec, explaining that?

I don't either sorry, it's just what I was able to make out of it. If I replace `01.84` by `0 1 0.84`, the rendering the the browser doesn't change and svgpath is able to parse it correctly

**Comment by puzrin** [comment]
Ah... those arc params are flags, which are 0 or 1, so, param scan should be terminated after matching digit found.

**Comment by puzrin** [comment]
Released with fix. Let me know how is it.

**Comment by hadihallak** [comment]
> What software used to generate such images? Some kind of SVG size optimizer?

You are correct. Designed in Figma then optimized using SVGO. disabling  `convertPathData` plugin seems to have fixed the issue but increased the size of SVGs

**Comment by puzrin** [comment]
Most size-effective optimization is removing fractional parts, if possible (except some arc params). Too aggressive spaces removal give very small effect and kill readability.

**Comment by mathieudutour** [comment]
> Let me know how is it.

Working fine now! Thanks a lot @puzrin 🙏

**Comment by kpym** [comment]
Just for information, when we save with InkScape with "optimized SVG" we can find this kind of paths `m305.07 118.43a125.26 116.17 0 00-125.26 116.17 125.26 116.17 0 001.4863 17.172h247.5a125.26 116.17 0 001.5332-17.172 125.26 116.17 0 00-125.26-116.17z` where we can see `00-125.26` that should be equivalent to `0 0 -125.26`, and the same for `001.4863` = `0 0 1.4863`. So this correction was right !
