### ISSUE TITLE
Is is possible to split segments

### ISSUE THREAD

**Issue by thednp** [fontello/svgpath#42]
Hi there.

I'm working on a new component for morphing SVGs and was wandering if your script can split segments somehow? Let me explain.

I am currently using some modified code from Raphael.js called `path2curve` which converts path commands to cubic-bezier, then replicates some of them in order to make both startShape and endShape have same amount of cubic-bezier points, but that's not always best in terms of visuals.

I need something that can normalize path commands by splitting long segments (in terms of length) into 2/more segments so that they're evenly distributed along both paths, and in the end have same number of points in both shapes.

Is this possible with your library?

**Comment by puzrin** [comment]
No, that's out of library scope.
