### ISSUE TITLE
Support for calculating bounding boxes

### ISSUE THREAD

**Issue by markvital** [fontello/svgpath#43]
Hi there,
Are there any plans to have support for calculating bounding boxes, similar to [SVGGraphicsElement.getBBox()](https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement/getBBox), except without rendering?
Here is an example:
```
var path = svgpath(__your_path__);
const {x, y, width, hight} = path.getBbox()
```
I'm using different library to calculate it for now, [SnapSVG](http://snapsvg.io/docs/#Element.getBBox), but I would like to use **svgpath** for everething, because it looks cleaner and smaller.

**Comment by puzrin** [comment]
See #17, please continue there if needed.

**Comment by markvital** [comment]
Are there any plans to merge this?
