### ISSUE TITLE
Support for reversing the path

### ISSUE THREAD

**Issue by markvital** [fontello/svgpath#44]
Are there any plans to have support for reversing the path?

```javascript
const path = svgpath(__your_path__)
const reversed = path.reverse();
```

| Direct Path   | Inverse Path  |
|:-------------:|:-------------:|
| <img src="http://i.imgur.com/yiqwvS7.png" width="250"> | <img src="http://i.imgur.com/V2xjCfK.png" width="250"> |
| `d="M50,300 L50,250 C50,150 75,150 100,250 C150,450 200,450 200,250 Q200,100 400,100"`  | `d="M400,100 Q200,100 200,250 C200,450 150,450 100,250 C75,150 50,150 50,250 L50,300"`|

**Comment by puzrin** [comment]
This looks specific. Could you explain use case?

**Comment by kpym** [comment]
Use case, that I can imagine, for reversing path is for example when you have two concentric circles and you want to fill in between. One way to do this is to revers the direction of one of them.

**Comment by puzrin** [comment]
@kpym thanks! Then question is - how often this is needed (how many people for), and should it be part of this lib or in extension.

**Comment by markvital** [comment]
I'm building SVG-based graphics editor. I will need to change direction of the arrow in the path connector (just like on the picture above). 
Adobe illustrator has similar function called "Reverse Path Direction".

The other use case would be changing fill rule for compound path.
SVG relies on path direction to define [rule](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule) how to fill shapes.

Also changing direction would be useful for animating line drawing of the path (using CSS3 or Javascript)

It would be great to have everything in one library

**Comment by markvital** [comment]
Here is visual example for the 2nd use case with compound path.
| Normal Path   | Middle math is inverted  |
|:-------------:|:-------------:|
| <img src="https://user-images.githubusercontent.com/742796/83304743-3c88b980-a1b4-11ea-81b9-62bf62051781.png" width="250"> | <img src="https://user-images.githubusercontent.com/742796/83304707-2da20700-a1b4-11ea-9813-576762669c0e.png" width="250"> |
| <sub>`d="M175,100a75,75,0,1,1-75-75A75,75,0,0,1,175,100Z M100,50a50,50,0,1,0,50,50A50,50,0,0,0,100,50Z m0,25a25,25,0,1,0,25,25A25,25,0,0,0,100,75Z"`</sub>  | <sub>`d="M175,100a75,75,0,1,1-75-75A75,75,0,0,1,175,100Z M100,50a50,50,0,1,1-50,50A50,50,0,0,1,100,50Z m0,25a25,25,0,1,0,25,25A25,25,0,0,0,100,75Z"`</sub>

**Comment by puzrin** [comment]
@markvital i know how contour direction related to filling. Question is different - should this be part of this lib or not:

1. If i start accept everything users can imagine, api become cluttered very soon.
2. Nobody can prohibit you to create extension package (which adds new method).

**Comment by markvital** [comment]
I understand, this make sense.
I thought reversing path is quite common feature and could be useful to anyone.
I definitely can find it somewhere else on the internet, but It would be great to have it all in one library, with all generic methods for working with SVG path in one place, well tested and supported.

**Comment by puzrin** [comment]
> I thought reversing path is quite common feature and could be useful to anyone.

You can check tracker history. During 6 years, bounding box was requested some times (not often, but > 1). Reverse - never.

IMO reverse looks specific for "editors", it's not used in more frequent cases like "automated transforms" (for example, "convert many SVG images to SVG font").

**Comment by markvital** [comment]
What do you mean by "tracker history"?
Is support for compound path (with multiple subpaths) out of scope too?

**Comment by puzrin** [comment]
> What do you mean by "tracker history"?

https://github.com/fontello/svgpath/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed

> Is support for compound path (with multiple subpaths) out of scope too?

If you mean multiple contours of [path data](https://www.w3.org/TR/SVG11/paths.html#PathData) - those are already suppored. If you mean something different - please explain.

**Comment by puzrin** [comment]
BTW, svgpath not includes everything for my own needs too :). See https://github.com/fontello/cubic2quad.

**Comment by markvital** [comment]
I see, fair enough.

By [compound path support](url) I mean being able to differentiate between single and multiple contours in one path and handle each sub-path separately.
Right now path string is parsed into flat Array structure, so I have to manually extract every sub-path, looking for "m", "M", and "Z" as a boundary between 2 sub-paths:
<img width="534" alt="Screen Shot 2020-05-29 at 6 28 26 PM" src="https://user-images.githubusercontent.com/742796/83316415-6a80f480-a1da-11ea-9327-2812fc537262.png">

**Comment by puzrin** [comment]
IMO, countours split task is:

a) specific
b) primitive (has trivial implementation, `string.split(/(?<=[zZ])\s*(?=[mM])/g)`)

=> not a good candidate.

Consider `svgpath` not as lib with thousand of method, but as engine easy to extend.

May be, it worth add `SvgPath.from()` (like `Array.from()`) for easy data clone.

**Comment by kpym** [comment]
I agree that `reverse` is more editor feature than automation one. This goes against integrating `reverse` in this library. But on the other side `reverse` footprint is very small : short code and easy documentation.

Another "editor" use case is when we want to join two paths by attaching the end of one of them to the start of the other. And this can be seen as an "automation" case, may be, join "head to head" or "tail to tail" two paths in a single one.

**Comment by puzrin** [comment]
I did not declined `.reverse()` yet. IMO, those are candidates to add by priority:

1. `.from()` - useful for clone-related things in extentions
2. `.bbox() => [x, y, w, h]` - PR closed, but feature not declined
3. `.reverse()` - just because not trivial but small, and fits well into svgpath api.

If (2) & (3) cost no much time for me [read as "your code can be reused" :)] - i have no principal objection and can prepare commits.

**Comment by kpym** [comment]
@puzrin I'd like to help you, but I don't have time right now, sorry. If you reuse the `reverse` of my fork, you have to be careful because I just saw that two lines of code are outside the function (probably bad copy/paste). I have to correct that. And tests are missing for both `reverse` and `bbox`.

**Comment by puzrin** [comment]
https://github.com/fontello/svgpath/commit/9258b7c8f0f0b0c2557f29468db14f8564dc89ce added `.from()`

https://github.com/fontello/svgpath/commit/dbdef3c8d460235651503c17d2107ebaa3356a07 (in separate branch) tried to copypaste .reverse() with appropriate changes. Tests existed, but broken (data compare fails). I have no plans to dive into that. If anyone wish to invesigate and make correct PR, it will be merged. If not - issue will be closed by timeout (because i don't keep issues which nobody plans to implement)

**Comment by markvital** [comment]
> IMO, countours split task is:
> b) primitive (has trivial implementation, `string.split(/(?<=[zZ])\s*(?=[mM])/g)`)

Thanks, the regexp is very helpful. Although, I don't understand: why do I need to run the regexp one more time  if I already parsed string using `svgpath()` function? I could just iterate over the `segments` array, right?

9258b7c looks useful, but how does it help to separate contours into different path objects?
It looks like I still have to manually manipulate `segments` array, splitting it into several arrays (one per sub-path). Factory-method `from()` accepts only `string` or another `SvgPath` object, so I can't 'feed' new path segment to it. I mean this:
```javascript
const path = svppath(some_complex_path);
//split compound path into countours by interating segments array and finding 'm','M' markers
const [contour1Arr, countour2Arr] = splitIntoCountours(path.segments); 
const simplePath1 = SvgPath.from(contour1Arr); // is this possible?
const simplePath2 = SvgPath.from(countour2Arr);
```

**Comment by markvital** [comment]
BTW, why `segments` array has the following structure?
```javascript
[
  ["M", 38.1, 22.5]
  ["C"  111.6, 76.5, 97.35, 61.2, 85, 48.8]
]
```
I know that heterogeneous Arrays are allowed in JavaScript, but isn't it a bad practice?

Wouldn't it be more convenient to store it like this?
```javascript
[
  {
    op: "M", //operation, always String
    data:[38.1, 22.5] //data points, always Number
  },
  {
    op: "C",
    data: [111.6, 76.5, 97.35, 61.2, 85, 48.8]
  }
]
```
Or at least like this?
```javascript
[
  [ "M", [38.1, 22.5] ],
  [ "C",  [111.6, 76.5, 97.35, 61.2, 85, 48.8] ]
]
```

**Comment by kpym** [comment]
@markvital your last proposal is also a heterogeneous arrays (string followed by array). 

Using array of structures looks more clean, but it is not really, because some of the numbers are `x` coordinates, some are `y` coordinates, some are relative, some are absolute, some are not even float number but 0/1 flags (in the arcs).  At first glance it looks better organized, but when you look deeper, it's not really, IMO. 

So simplicity wins vs deeper structures in this case ;)

**Comment by markvital** [comment]
I see, make sense.
Have you thought about adding static types to the library, like TypeScript?

**Comment by puzrin** [comment]
Let's close this (because nobody plan to implement, and issues should no be endless). If someone ever decide to prepare good PR,it will be accepted.

**Comment by markvital** [comment]
@puzrin Are there any docs how to contribute to the library? I mean the instructions how to develop it locally.

I tried to check out the branch dbdef3c with reverse():
```
# git checkout git@github.com:fontello/svgpath.git SVGPathRev
# cd SVGPathRev
# npm install
# npm run test
```
Got an error:
```
> svgpath@2.3.0 test /Users/svgMan/WebstormProjects/SVGPathRev
> npm run lint && nyc mocha


> svgpath@2.3.0 lint /Users/svgMan/WebstormProjects/SVGPathRev
> eslint .

/Users/svgMan/WebstormProjects/SVGPathRev/node_modules/eslint/bin/eslint.js:93
        } catch {
                ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
...
```
Am I missing something?
