### ISSUE TITLE
Support for open/closed path

### ISSUE THREAD

**Issue by markvital** [fontello/svgpath#45]
It would be great to have the ability to detect if the path is open/closed in **svgpath**.

![open-closed](https://user-images.githubusercontent.com/742796/83306262-1add0180-a1b7-11ea-86d7-74d58e59c600.png)

| `stroke="#9999CC" fill="none"` |`stroke="#9999CC" fill="none"` |
|:-------------:|:-------------:|
| `d="M5 8.5, 13.2c0, 79.9, 91.8, 79.9, 91.8, 159.7 Z"`  | `d="M 58.5, 13.2c0, 79.9, 91.8, 79.9, 91.8, 159.7 "`|

Fore example:

```javascript
const path = svgpath(__your_path__)
path.isOpen() // true or false
```

And corresponded methods for opening/closing the path.
```javascript
const path = svgpath(__your_path__)
path.close()
path.open()
```

**Comment by puzrin** [comment]
```js
function isOpen(str) {
	return !/[zZ]$/.test(str);
}
```

I don't like this request. It's specific for your app.

Please, don't consider svgpath as "lib or everything". It's goal is to make **frequent** sophisticated actions and be compact. This project is stable, and by default all requests are rejected. But if you think some feature is impotant:

1. You are expected to explain why it's useful for all (no only for you).
2. Someone should be ready to do PR.

And, as i said in another issue - you can create package for svgpath prototype extension, and get any set of methods independent on my opinion.
