### ISSUE TITLE
Support for more modular structure using ES6 modules

### ISSUE THREAD

**Issue by markvital** [fontello/svgpath#46]
Are the any plans to support more modularity for the library, using ES modules? So only the parts of it that are used could be imported using `import` or `require` instead of the whole library.
This will help to reduce the size of final Webpack bundle.

As I understand right now all functions like `scale`, `rotate` are incapsulated as the parts of the object `SvgPath`. If each function could return new copy of the object instead of mutating it, that it could make it completely independent so the function could be exported using ES6 `export` statement and imported lately.
 
For example:
```javascript
const {from, scale, round, toString} import from svgpath;

const aPath = from(_some_path); //returns new SVGPath object

const scaled = scale(aPath, 0.5); //returns new SVGPath object
const translated =translate(aPath, 100, 200); //returns new SVGPath object

console.log( toString(scaled) );
```

**Comment by puzrin** [comment]
@markvital please understand me right, this project is stable, I do another things and can't spend time for changes "just for fun".

**Comment by markvital** [comment]
OK, I understand, NP
