### ISSUE TITLE
Differentiate between relative chained and isolated command in parser

### ISSUE THREAD

**Issue by mondeja** [fontello/svgpath#49]
Hi. First of all, thank you very much for this utility, it's awesome!

In [simple-icons](https://github.com/simple-icons/simple-icons) we are using svgpath a lot to [lint paths](https://github.com/simple-icons/simple-icons/blob/45130ca86afc0e8818eece751e75d9e22c95e823/.svglintrc.js). I was wondering if it might be possible to differentiate between a chained relative segment and an isolated one. For example, the set of chained segments `l-.014-.076-.01-.04-.012-.048` are parsed as three segments, and there's no way to tell them apart from `l-.014-.076l-.01-.04l-.012-.048`. With this functionality we could be able to show more accurate error messages in the linter.

**Comment by puzrin** [comment]
Sorry, no way.
