### ISSUE TITLE
rel method Supports Typescript

### ISSUE THREAD

**Issue by jayson991** [fontello/svgpath#50]
In my typescript project **rel** method has a problem: **_Property 'rel' does not exist on type 'SvgPath'.ts(2339)_**, There must be something wrong about  **rel** method.
![image](https://user-images.githubusercontent.com/21055290/107199983-151c0900-6a32-11eb-9ddd-dc2d216e044f.png)
Here is **rel** method type missing.

**Comment by puzrin** [comment]
We do not support TS, sorry. Definition file is driven by volunteer's PR's.

If anyone knows TS and knows how to improve defs - just do PR.
