### ISSUE TITLE
Instructions for running locally

### ISSUE THREAD

**Issue by blakegearin** [fontello/svgpath#53]
Hello, I noticed your README doesn't list how to clone this repository and get the code running locally. Would you be able to share some steps for this?

**Comment by puzrin** [comment]
This is not specific to this package. Readme size is not endless, and already user for more important things.

**Comment by blakegearin** [comment]
I wasn't asking for a README update, I was asking for steps because they're not included anywhere as far as I can tell.

The whole point of open-source code is being able to download, run locally, and identify fixes/improvements. If people don't know how to do that it might as well be closed-source.

**Comment by puzrin** [comment]
IMO you asking generic programming question, not specific for this package. It's better use google/stacjoverflow for that.

**Comment by blakegearin** [comment]
...so you're wanting to limit who contributes to this package based on who can search online on third-party websites for the right "generic programming" questions? That's called gatekeeping.

**Comment by puzrin** [comment]
I do not provide free personal consultations about programming. Please, stop waste my time. If you have permission to write here by default, that does not mean any kind of postings are welcome.
