### ISSUE TITLE
very high cpu usage 

### ISSUE THREAD

**Issue by humbleCoder1990** [fontello/svgpath#62]
I'm using "svgpath" heavily to draw svg in <cavas> like this.

![image](https://user-images.githubusercontent.com/87828192/193184209-c53ea770-bc66-4000-8ba9-f03d90e47e91.png)

The problem is it uses very high cpu.
Without "svgpath" it usaully costs 10%.
But as soon as I use it, it goes to 40%.
Because I draw 20~30svgs.

Is there any solution? I guess it's very heavy math + a lot of string parsing..

**Comment by puzrin** [comment]
If you have a lot ot data, parse can take some time, because speed is not infinite.

**Comment by Kaiido** [comment]
This comment is not really related to this lib, sorry,  but why don't you use your Canvas2D context to perform the transform? With `fill()` that shouldn't be an issue (strokes would get scaled too though).
Or you could even do
```
const p1 = new Path2D();
p1.addPath(new Path2D("your long path"), { a: scale, d: scale, e: translateX * scale, f: translateY * scale }));
ctx.fill(p1);
``` 
And if you really do parse that many path-data every frame, you might consider storing the resulting `Path2D` objects.
