### ISSUE TITLE
Support transformation units

### ISSUE THREAD

**Issue by dtgreene** [fontello/svgpath#65]
Is it possible to partially support transformation units such as `deg`, `rad`, `px`? Currently, transform parameters are converted to numbers which fails with units and results in the parameters being zero.

Here's the snippet from [transform_parse.js](https://github.com/fontello/svgpath/blob/master/lib/transform_parse.js#L19):

```javascript
    params = item.split(PARAMS_SPLIT_RE).map(function (i) {
      return +i || 0;
    });
```

I think a potentially easy fix would be to just strip away the units while potentially converting others:

```javascript
    var UNITS_SPLIT_RE = /\d+/;
    var RAD_TO_DEG = 180 / Math.PI;
    var TWO_PI = Math.PI * 2;

    // ...

    params = item.split(PARAMS_SPLIT_RE).map(function (param) {
      let value = Number(param.match(UNITS_SPLIT_RE)[0]) || 0;
      let unit = param.replace(value, '');

      switch (unit) {
        case 'rad': {
          value = value * RAD_TO_DEG;
          break;
        }
        case 'turn': {
          value = value * TWO_PI * RAD_TO_DEG;
          break;
        }
        case 'in': {
          value = value * 96;
          break;
        }
      }

      return value;
    });
```

**Comment by puzrin** [comment]
This package was designed for SVG path transforms, and follows existing markup standards. The things you ask are out of scope. You probably need to pre-process data before the call.
